---
- name: install php
  apt: name={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-dev
    - php5-json
    - php5-zmq

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: enable php errors showing
  lineinfile: dest=/etc/php5/apache2/php.ini line="display_errors = On"
  lineinfile: dest=/etc/php5/cli/php.ini line="display_errors = On"

- name: enable php startup errors showing
  lineinfile: dest=/etc/php5/apache2/php.ini line="display_startup_errors = On"
  lineinfile: dest=/etc/php5/cli/php.ini line="display_startup_errors = On"

- name: enable php error reporting
  lineinfile: dest=/etc/php5/apache2/php.ini line="error_reporting = E_ALL | E_STRICT"
  lineinfile: dest=/etc/php5/cli/php.ini line="error_reporting = E_ALL | E_STRICT"

- name: enable php short open tags
  lineinfile: dest=/etc/php5/apache2/php.ini line="short_open_tag = On"